apiVersion: v1
kind: Service
metadata:
  name: specialistsearch-svc
spec:
  selector:
    app: specialistsearch
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
